{% set name = "stdpopsim" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ad76257ff3a75eac7f5a696405f14bbabb1fcda783beaa9db716995dac8f5a7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - stdpopsim=stdpopsim.cli:stdpopsim_main
  noarch: python

requirements:
  host:
    - setuptools
    - setuptools_scm
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msprime >=1.0.4
    - attrs >=19.1.0
    - pyslim >=1.0.1
    - appdirs
    - humanize
    - numpy
    - slim
    # Note: these three dependencies will probably be removed soon
    # https://github.com/popsim-consortium/stdpopsim/issues/1412
    # https://github.com/popsim-consortium/stdpopsim/pull/1416
    - pandas
    - zarr
    - scipy

test:
  requires:
    - python {{ python_min }}
  commands:
    - stdpopsim -h
  imports:
    - stdpopsim

about:
  home: http://github.com/popsim-consortium/stdpopsim
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A community-maintained standard library of population genetic simulations
  description: |
    Stdpopsim provides a standard library of population genetic simulations, based
    around a catalog of species definitions, empirical genetic maps and demograpic
    models.
  doc_url: https://popsim-consortium.github.io/stdpopsim-docs/
  dev_url: https://github.com/popsim-consortium/stdpopsim

extra:
  recipe-maintainers:
    - jeromekelleher
    - petrelharp
