{% set name = "stdpopsim" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9ec4f3f63322a2414f1bb566899ba7f8ae0fc25de776102b27c5ffc98f83249

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - stdpopsim=stdpopsim.cli:stdpopsim_main
  noarch: python

requirements:
  host:
    - setuptools
    - setuptools_scm
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - msprime >=0.7.1
    - attrs >=19.1.0
    - pyslim >=0.401
    - appdirs
    - humanize

test:
  commands:
    - stdpopsim -h
  imports:
    - stdpopsim

about:
  home: http://github.com/popsim-consortium/stdpopsim
  license: GPLv3+
  license_family: GPL
  license_file: LICENSE
  summary: A community-maintained standard library of population genetic simulations
  description: |
    Stdpopsim provides a standard library of population genetic simulations, based
    around a catalog of species definitions, empirical genetic maps and demograpic
    models.
  doc_url: http://stdpopsim.readthedocs.io/
  dev_url: https://github.com/popsim-consortium/stdpopsim

extra:
  recipe-maintainers:
    - jeromekelleher
